---
- hosts: local
  gather_facts: no
  vars:
    - cluster_type: "{{ cluster_type }}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - druid